# Generated by Django 4.2.4 on 2023-09-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_perros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='fotoPerro',
            field=models.ImageField(blank=True, null=True, upload_to='perros'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='imagenPerro',
            field=models.ImageField(blank=True, null=True, upload_to='perros/'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='sexoPerro',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=3),
        ),
    ]
