# Generated by Django 4.2.4 on 2023-09-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_perros', '0002_alter_publicacion_sexoperro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='sexoPerro',
            field=models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=3),
        ),
    ]
