# Generated by Django 4.2.4 on 2023-10-16 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_perros', '0002_remove_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotoPerfil', models.ImageField(blank=True, null=True, upload_to='./perfil')),
                ('nombrePerfil', models.CharField(max_length=30)),
                ('apellidoPerfil', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
                ('localidad', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
