# Generated by Django 4.2.5 on 2023-09-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_perros', '0003_remove_publicacion_imagenperro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fotoPerro',
            field=models.ImageField(blank=True, null=True, upload_to='./media/perros'),
        ),
    ]
