# Generated by Django 4.2.5 on 2023-10-19 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_perros', '0003_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='fotoPerfil',
        ),
    ]
