# Generated by Django 4.2.4 on 2023-09-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_perros', '0004_alter_publicacion_fotoperro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='tamañoPerro',
            new_name='tamanioPerro',
        ),
    ]
