# Generated by Django 4.2.4 on 2023-09-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_perros', '0005_rename_tamañoperro_publicacion_tamanioperro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='sexoPerro',
            field=models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=3),
        ),
    ]
