# Generated by Django 4.2.5 on 2023-10-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_perros', '0007_publicacion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='castradoPerro',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=5),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='desparasitadoPerro',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=5),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='libretaPerro',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=5),
        ),
    ]
