# Generated by Django 4.2.5 on 2023-10-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_perros', '0012_alter_publicacion_castradoperro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='vacunadoPerro',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=5),
        ),
    ]
