# Generated by Django 4.2.5 on 2023-10-31 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_perros', '0013_publicacion_vacunadoperro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='castradoPerro',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='False', max_length=5),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='desparasitadoPerro',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='False', max_length=5),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='libretaPerro',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='False', max_length=5),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='vacunadoPerro',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='False', max_length=5),
        ),
    ]
