# Generated by Django 4.2.5 on 2023-11-06 02:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_perros', '0014_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='favorito',
            field=models.ManyToManyField(blank=True, related_name='favorito', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Favorito',
        ),
    ]
