# Generated by Django 4.2.6 on 2023-11-11 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_perros', '0014_perfil_biografia_perfil_fotoperfil'),
        ('pagina_perros', '0016_remove_publicacion_favorito_favorito'),
        ('pagina_perros', '0022_alter_publicacion_usuario'),
    ]

    operations = [
    ]
