# Generated by Django 4.2.5 on 2023-11-07 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_perros', '0016_remove_publicacion_favorito_favorito'),
        ('pagina_perros', '0022_alter_publicacion_usuario'),
    ]

    operations = [
    ]
