# Generated by Django 5.0.4 on 2024-04-09 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_perros', '0023_merge_20231107_1255'),
        ('pagina_perros', '0023_merge_20231111_0008'),
    ]

    operations = [
    ]
