# Generated by Django 5.0.4 on 2024-04-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_perros', '0024_merge_20240409_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fotoPerfil',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fotoPerro',
            field=models.CharField(blank=True, null=True),
        ),
    ]
