# Generated by Django 5.0.4 on 2024-04-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_perros', '0027_alter_publicacion_fotoperro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fotoPerfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles'),
        ),
    ]
